# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37f94528cd2fd51483f744e313f527e1f0da6c5b6aa529391189041ec1e789ef3737be76ff67df396d2ba897ffd9331f3e4c0330092fefa1356edaec2cc0814c

test:
  secret_key_base: 9169b657e983c2469a65fa32a55ff70c3811648b3e26280a505dba1e185ad8e9016d90b1ecf422895b7fde2d49ef42dac644206b3e7136c462d33f005c297ebf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
